# Generated by Django 4.1.7 on 2023-02-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('image', models.CharField(max_length=500, verbose_name='Image')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('leftover', models.PositiveIntegerField(verbose_name='Leftover')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
        ),
    ]
